# Generated by Django 2.2.10 on 2021-07-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1023, verbose_name='Текст вопроса')),
                ('type_of_question', models.CharField(max_length=255, verbose_name='Тип ответа')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.AlterField(
            model_name='interview',
            name='description',
            field=models.CharField(max_length=1023, verbose_name='Описание опроса'),
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст варианта')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Вопрос', to='interviews.Question')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Опрос', to='interviews.Interview'),
        ),
    ]
