# Generated by Django 2.2.10 on 2021-07-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_auto_20210714_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='date_of_end',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='date_of_start',
        ),
    ]
