# Generated by Django 2.2.10 on 2021-07-14 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_auto_20210714_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='date_of_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания опроса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview',
            name='date_of_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала опроса'),
            preserve_default=False,
        ),
    ]
