# Generated by Django 2.2.10 on 2021-07-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_auto_20210714_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variant',
            new_name='OptionOfAnswer',
        ),
        migrations.AlterField(
            model_name='question',
            name='type_of_answers',
            field=models.PositiveIntegerField(default=1, verbose_name='Тип ответа'),
        ),
    ]
